### ISSUE TITLE
error in test module

### ISSUE THREAD

**Issue by mrinalraj** [SunJieMing/js-minicamp-homework-1#2]
in test.js roundUp() function call has the property of roundNumber..
the answer expected from roundUp function is that expected from roundNumber..
error log says 

```
 roundUp(num)                                                                                                                                                              
    × should return the argument after squaring it (4ms) 
```

test.js 139:5
please fix it

**Comment by mrinalraj** [comment]
i have fixed it here..
checkout if you want 

https://github.com/mystiquemilo/js-minicamp-homework-1

**Comment by SunJieMing** [comment]
Updated.  Thanks!
