### ISSUE TITLE
Prism Volume Typo

### ISSUE THREAD

**Issue by ghost** [SunJieMing/js-minicamp-homework-1#6]
tests/test.js line 190:

`it('should return the correct area', function() {`

Should be:

`it('should return the correct volume', function() {`

exercises.js line 135:

`//return the area of the 3D rectangular prism given the length, width, and height`

Should be:

`//return the volume of the 3D rectangular prism given the length, width, and height`

**Comment by SunJieMing** [comment]
Updated, thanks!
